allow-branch = ["main", "develop", "!HEAD"]
publish = true
pre-release-commit-message = "chore: Release version {{version}}"
tag-message = "chore: Release version {{version}}"
tag-name = "v{{version}}"
