[package]
name = "grow_sqlx"
description = "A internal librarie for grow"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8.1"
sqlx = { version = "0.8.2", features = ["runtime-async-std", "sqlite", "postgres", "mysql", "macros", "migrate"] }

