name: CI Checks
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - ".github/"
      - "static/"
      - "**/Makefile.toml"
      - "release.toml"
      - "LICENSE*"
      - "README.md"
      - "CONTRIBUTING.md"
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  # Run cargo clippy -- -D warnings
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Run clippy
        run: cargo clippy -- -D warnings

  # Run cargo test
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test
